Left bar component menu + AdministratorPanel + Manage Administrator
eugenek7/.NET-team-2 pull request #20
Opened 2022-07-26 07:52 UTC by SerhiiTarasiuk

2022-07-26 08:19 UTC, AhnessP commented on EasyRestProjectNetTeam2/EasyRestPages/AdministratorManagePage.cs
> +            _inputPhoneNumberForNewAdministrator.SendKeys(phonenumber);
please rename  phoneNumber for  better readability

2022-07-26 08:25 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestComponentsObj/LeftBarMenuComponent.cs
> +
please remove empty lines

2022-07-26 08:26 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestPages/AdministratorManagePage.cs
> +
please remove useless lines, but leave one line between locator and method

2022-07-26 08:27 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestPages/AdministratorPanelPage.cs
> +        public void ClickToGetInfoAboutOrderArrow()    //First one in the list
Is the comment actual for that method?

2022-07-26 08:27 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestPages/MenuPage.cs
> +
please remove the empty line

2022-07-26 08:28 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestPages/MenuPage.cs
>          public MenuPage(IWebDriver driver) : base(driver)
please add one line between property and constructor for better readability

2022-07-26 08:28 UTC, dmatsev requested changes
Please resolve the comments.

2022-07-27 06:17 UTC, Slim1011 approved these changes

2022-07-27 08:07 UTC, AhnessP approved these changes

2022-07-27 08:39 UTC, dmatsev approved these changes

2022-07-27 08:42 UTC, merged