Check waiter panel tests
eugenek7/.NET-team-2 pull request #53
Opened 2022-08-19 12:36 UTC by AhnessP

2022-08-21 13:48 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestTests/CheckWaitersTests.cs
> +        public override void TearDown()
should you add `[Teardown]` attribute?

2022-08-21 13:51 UTC, AhnessP commented on EasyRestProjectNetTeam2/EasyRestTests/CheckWaitersTests.cs
> +        public override void TearDown()
fixed

2022-08-21 14:05 UTC, dmatsev requested changes
Please fix the solution.

2022-08-21 14:25 UTC, dmatsev commented on EasyRestProjectNetTeam2/EasyRestTests/CheckWaitersTests.cs
> +
please remove empty lines

2022-08-21 14:31 UTC, AhnessP commented on EasyRestProjectNetTeam2/EasyRestTests/CheckWaitersTests.cs
> +
fixed

2022-08-21 14:52 UTC, dmatsev approved these changes

2022-08-22 07:14 UTC, SerhiiTarasiuk approved these changes

2022-08-22 07:53 UTC, merged